# Generated by Django 3.2.4 on 2021-06-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210620_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_ru',
            field=models.TextField(verbose_name='Izoh (ru)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_uz',
            field=models.TextField(verbose_name='Izoh (uz)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject_ru',
            field=models.CharField(max_length=100, verbose_name='Sarlavha (ru)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject_uz',
            field=models.CharField(max_length=100, verbose_name='Sarlavha (uz)'),
        ),
    ]
