# Generated by Django 3.2.4 on 2021-08-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='comment',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='header',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
