# Generated by Django 3.2.4 on 2021-08-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210825_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Faol'), (0, 'Nofaol')], default=1),
        ),
    ]
