# Generated by Django 3.2.4 on 2021-08-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_carousel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
